local agents = require "example.scripts.agents"
local const  = require "example.scripts.const"
local data   = require "example.scripts.data"
go.property("arc_buffer", resource.buffer("/example/assets/arc_1_navmesh.buffer"))

local mouse_position = vmath.vector3()
local start_position = vmath.vector3()
local goal_position  = vmath.vector3()
local COLORS         = {
	RED = vmath.vector4(1, 0, 0, 1),
	GREEN = vmath.vector4(0, 1, 0, 1),
	BLUE = vmath.vector4(0, 0, 1, 1)
}

local path_size      = 0
local status         = -1
local status_text    = ""
local path           = {}

local cam            = msg.url("/camera#camera")
local EPS            = 1e-6
local PLANE_POINT    = vmath.vector3(0, 0, 0)
local PLANE_NORMAL   = vmath.vector3(0, 1, 0)

local function screen_to_plane(cam, sx, sy)
	local p0 = camera.screen_to_world(vmath.vector3(sx, sy, 0), cam)
	local p1 = camera.screen_to_world(vmath.vector3(sx, sy, 1), cam)

	local dir = p1 - p0
	local denom = vmath.dot(PLANE_NORMAL, dir)
	if math.abs(denom) < EPS then
		return nil
	end

	local t = vmath.dot(PLANE_POINT - p0, PLANE_NORMAL) / denom
	if t < 0 then
		return nil
	end

	return p0 + dir * t
end

local function find_path()
	path_size, status, status_text, path = pathfinder.navmesh_find_path(start_position.x, start_position.z, goal_position.x, goal_position.z, 128, 0.2)

	print(path_size, status, status_text)
	pprint(path)
end

function init(self)
	profiler.enable_ui(true)
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)
	msg.post(".", "acquire_input_focus")
	cam                    = msg.url("/camera#camera")
	data.path_smoothing_id = pathfinder.add_path_smoothing(const.SMOOTHING_CONFIG)

	pathfinder.navmesh_init(600, 6, 32, 16, 256, 5, 10, 1000)

	--	pprint(self.arc_buffer) --  hash: [/example/assets/arc_1_navmesh.bufferc]

	local arc_buffer = resource.get_buffer(self.arc_buffer)
	pprint(arc_buffer) -- buffer.buffer(count = 744, version = 0, handle = 65536, { hash("position"), buffer.VALUE_TYPE_FLOAT32, 3 })
	--	local stream_positions = buffer.get_stream(arc_buffer, "position")
	--	print(stream_positions) --  buffer.bufferstream({ hash("position"), buffer.VALUE_TYPE_FLOAT32, 3 })
	pathfinder.navmesh_set_buffer(arc_buffer)
end

-- Draw a path as red lines connecting waypoints
local function draw_node_to_node(path_size, path)
	for i = 1, path_size - 1, 1 do
		local from_node = path[i]
		local to_node = path[i + 1]

		msg.post("@render:", "draw_line", { start_point = vmath.vector3(from_node.x, 0, from_node.y), end_point = vmath.vector3(to_node.x, 0, to_node.y), color = COLORS.RED })
	end
end

function update(self, dt)
	draw_node_to_node(path_size, path)
	agents.update(dt)
end

local lpress = false

function on_input(self, action_id, action)
	if action.x then
		mouse_position.x = action.x
		mouse_position.y = action.y
	end

	if action_id == hash("left_shift") and action.pressed then
		lpress = true
	end

	if action_id == hash("left_shift") and action.released then
		lpress = false
	end
	if not lpress then
		if not action.pressed then return end


		if action_id == hash("mouse_button_left") then
			local hit = screen_to_plane(cam, action.screen_x, action.screen_y)
			start_position = hit
			go.set_position(hit, "/start")
		elseif action_id == hash("mouse_button_right") then
			local hit = screen_to_plane(cam, action.screen_x, action.screen_y)
			goal_position = hit
			go.set_position(hit, "/end")
		end

		if action_id == hash("space") and action.pressed then
			agents.add(start_position, goal_position)
		end
	end
end
