go.property("navmesh_buffer", resource.buffer("/example/assets/navmesh.buffer"))

local agents             = require "example.scripts.agents"
local const              = require "example.scripts.const"
local data               = require "example.scripts.data"
local draw               = require "example.scripts.draw"
local utils              = require "example.scripts.utils"

-- =================================
-- VARIABLES
-- =================================
local mouse_position     = vmath.vector3()
local start_position     = vmath.vector3()
local goal_position      = vmath.vector3()
local cam                = msg.url()
local spatial_index_grid = {}
local shift_pressed      = false
local navmesh_id         = 0

--==========================================================
-- FUNCTIONS
--==========================================================
local function validate_spawn_point(x, y)
	local cell_id, center_x, center_y = pathfinder.navmesh_cell_at_position(navmesh_id, x, y)

	if cell_id ~= pathfinder.INVALID_ID then
		print("Position is walkable, in cell", cell_id)
		print("Cell center:", center_x, center_y)
		return true
	else
		print("Position is not walkable (outside navmesh): ", x, y)
		return false
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	profiler.enable_ui(true)
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)

	local navmesh_buffer   = resource.get_buffer(self.navmesh_buffer)
	cam                    = msg.url("/camera#camera")
	data.path_smoothing_id = pathfinder.add_path_smoothing(const.SMOOTHING_CONFIG)



	navmesh_id = pathfinder.navmesh_init(300, 32, 32, 128, 5, 10, 1000, true)


	pathfinder.navmesh_set_buffer(navmesh_id, navmesh_buffer)
	spatial_index_grid = pathfinder.navmesh_get_spatial_index(navmesh_id)

	start_position = go.get_position("/path_start")
	goal_position = go.get_position("/path_end")


	-- Example 8: Validate Cell at position
	validate_spawn_point(start_position.x, start_position.z)
	validate_spawn_point(100, 100)
end

function update(self, dt)
	draw.grid(spatial_index_grid)
	agents.update(dt)

	local stats = pathfinder.navmesh_get_stats(navmesh_id)
	-- pprint(stats)
end

function on_input(self, action_id, action)
	if action.x then
		mouse_position.x = action.x
		mouse_position.y = action.y
	end

	-- Hold LEFT SHIFT for camera and rotate with RIGHT MOUSE BUTTON
	if action_id == const.TRIGGERS.LEFT_SHIFT then
		if action.pressed then
			shift_pressed = true
		elseif action.released then
			shift_pressed = false
		end
	end

	if not shift_pressed then
		if not action.pressed then return end

		if action_id == const.TRIGGERS.MOUSE_BUTTON_LEFT then -- LEFT CLICK for start position
			start_position = utils.screen_to_plane(cam, action.screen_x, action.screen_y)
			go.set_position(start_position, "/path_start")
			validate_spawn_point(start_position.x, start_position.z)
		elseif action_id == const.TRIGGERS.MOUSE_BUTTON_RIGHT then -- RIGHT CLICK for goal position
			goal_position = utils.screen_to_plane(cam, action.screen_x, action.screen_y)
			go.set_position(goal_position, "/path_end")
			validate_spawn_point(goal_position.x, goal_position.z)
		end

		-- Press SPACE to add agent
		if action_id == const.TRIGGERS.SPACE and action.pressed then
			agents.add(navmesh_id, start_position, goal_position)
		end
	end
end
